### ISSUE TITLE
💄 Mates, User 퍼블리싱 to-do

### ISSUE THREAD

**Issue by 529539** [KUDDY-2023/KUDDY-front#14]
### mates
- [ ] 메이트 전체 페이지
- [ ] 메이트 검색 페이지

### user
- [ ] 마이페이지
- [ ] 티켓 인증 페이지
- [ ] 내가 쓴 글, 내가 댓글 단 글 조회 페이지

<br>
