### ISSUE TITLE
💄 퍼블리싱 to-do

### ISSUE THREAD

**Issue by 529539** [KUDDY-2023/KUDDY-front#3]
### 관광지
- [ ] 홈 페이지
- [ ] 하단 네비게이션 바
- [ ] 장소 전체 페이지
- [ ] 장소 검색 페이지
- [ ] 장소 상세 페이지
- [ ] 장소를 찜한 메이트
- [ ] 북마크한 장소 페이지

### 매거진 & 부가 기능 메뉴
- [ ] 커디스픽 전체 페이지
- [ ] 커디스픽 상세 페이지
- [ ] 유튜브 페이지 
- [ ] 위치 기반 추천 페이지 (카카오맵)

### 메이트
- [ ] 메이트 전체 페이지
- [ ] 메이트 검색 페이지

### 유저
- [ ] 마이페이지
- [ ] 티켓 인증 페이지
- [ ] 내가 쓴 글, 내가 댓글 단 글 조회 페이지

<br>
